### ISSUE TITLE
incoming issues

### ISSUE THREAD

**Issue by NC-MXTC** [MarcosSanchezAV/NCTaskManager#1]
https://github.com/MarcosSanchezAV/NCTaskManager/blob/758b78373f81f6bf5ecc217edae2402777254c78/src/main/java/mx/tc/j2se/tasks/ArrayTaskListImpl.java#L67-L87

Doesn't this remind you of something you have done before and is available in TaskImpl?

**Comment by NC-MXTC** [comment]
https://github.com/MarcosSanchezAV/NCTaskManager/blob/f4ab8bba4811ed5ac68c2d5578eba2e5ff7f2819/src/main/java/mx/tc/j2se/tasks/LinkedTaskListImpl.java#L78-L105

Same for P3

**Comment by mdsanz** [comment]
Yes of course, I modified the method and now it can be implemented in an abstract class
