### ISSUE TITLE
Add issue

### ISSUE THREAD

**Issue by NC-MXTC** [MarcosSanchezAV/NCTaskManager#2]
https://github.com/MarcosSanchezAV/NCTaskManager/blob/f4ab8bba4811ed5ac68c2d5578eba2e5ff7f2819/src/main/java/mx/tc/j2se/tasks/LinkedTaskListImpl.java#L30-L34

You only have a reference to the head, but you are adding to the end of the list. Maybe there is something else you can have to avoid this add O(n) complexity.

**Comment by mdsanz** [comment]
I resolved this creating a new attribute called queue and represents the end of the linked list, so every time we need add a new task, it's only attached to the last node
